### ISSUE TITLE
when "make " mistake: no python.h

### ISSUE THREAD

**Issue by CloudsRL** [iit-DLSLab/Panoptic-SLAM#2]
Hello, when i make orb-slam3, i face a mistake:

/home/wang/code/Panoptic-SLAM/include/PanopticNet.h:22:10: fatal error: Python.h: 没有那个文件或目录
   22 | #include <Python.h>
      |          ^~~~~~~~~~

but i have not found how to deal with it. So if possible, please help me
(what i care is , how to use python in c++ program, i am trying to make it)

**Comment by git-gfischer** [comment]
Hi! Are you installing via docker or on your host PC?

**Comment by CloudsRL** [comment]
no QAQ i don't know about DOCKER , i just follow the "Build Panoptic-SLAM on Host Machine", but not mention about how python work with cpp

**Comment by git-gfischer** [comment]
We recommend you to install through the dockerfile, because then all the dependencies will be installed automatic. It will be difficult for us to debug this on your host PC. We use the Python C API to communicate python and c++ applications, but pybind also works well. 

The problem you are facing might be either the API is not installed or the python version is not matching with the python version of the CMakeLists.txt.

**Comment by CloudsRL** [comment]
3ku so much, i have finish it [LOL]
i use conda to create env, and change the CMAKELIST.txt to suit it, after fix some bug i make it run 
bug like this :
PIL.Image  has no attribute ‘LINEAR’————>pip uninstall Pillow，and then pip install Pillow==8.4.0 -i https://pypi.mirrors.ustc.edu.cn/simple/ 
detectron2 np.bool mistakes————> change them into bool
and balabala i don't remember hahahaha
btw, i use cuda 11.1, the speed is 0.9~1.4 s/frame, maybe the lighter backbone will help
